### ISSUE TITLE
Make categories generator for single each term

### ISSUE THREAD

**Issue by dimaslanjaka** [hexojs/hexo-generator-category#78]
Make single category each terms like wordpress.

post meta example
```yaml
category: ['Games', 'The Legend Of Neverland']
```
result permalink looks like

[https://www.webmanajemen.com/categories/Games/](https://www.webmanajemen.com/categories/Games/)
[https://www.webmanajemen.com/categories/The-Legend-Of-Neverland/](https://www.webmanajemen.com/categories/The-Legend-Of-Neverland/)

Please refer to my issue here [https://github.com/hexojs/hexo/issues/5132](https://github.com/hexojs/hexo/issues/5132)

**Comment by dimaslanjaka** [comment]
is this work ? https://github.com/hexojs/hexo/issues/5132#issuecomment-1396995862

**Comment by uiolee** [comment]
It looks like this issue has been resolved and I will close it. 

If the problem persists, please **reopen**
